### ISSUE TITLE
c6-stereotype-threat.html

### ISSUE THREAD

**Issue by aklap** [cschlessinger/cschlessinger.github.io#29]
This was a nice post, Claire; well written with some nice insight into your personal experiences. I enjoyed learning a little bit more about your background and life before DBC, and I appreciate the ability to understand other's view points and experiences. My feedback is to continue staying open, vulnerable, and curious as you've demonstrated in your blog post. Good job!

**Comment by cschlessinger** [comment]
Thanks, Alexis!
